### ISSUE TITLE
Restrict out put result to a define no of content

### ISSUE THREAD

**Issue by rupam** [andferminiano/jquery-scroll-pagination#4]
Is there any way where I can only show a no of result instead of repeating the same content as given in the example? For example, I want to show only 20 result out of 100 first time and when user scroll down then next 20 and so on.

**Comment by pohoder** [comment]
To do so you just have to remove the lines given in an example, like this:

'afterLoad': function(elementsLoaded){
     $('#loading').fadeOut();
     var i = 0;
     $(elementsLoaded).fadeInWithDelay();  
        $('#nomoreresults').fadeIn();
        $('#newslist').stopScrollPagination();  
}
